# Generated by Django 4.2.3 on 2023-07-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='usuarios/curriculums'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='localidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='img/usuario_default.png', null=True, upload_to='usuarios/imagenes'),
        ),
    ]
