# Generated by Django 4.2.3 on 2023-07-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_edad_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='usuarios/usuario_default.png', null=True, upload_to='usuarios/imagenes'),
        ),
    ]
