# Generated by Django 4.2.3 on 2023-07-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='fecha_nacimiento'),
        ),
    ]
