# Generated by Django 4.2.3 on 2023-09-15 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=20)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, default='empleos/logo_default.png', null=True, upload_to='empleos')),
                ('administrador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('localidad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='empleos.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=40)),
                ('contenido', models.TextField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel_laboral', models.CharField(max_length=20)),
                ('carga_horaria', models.IntegerField()),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('modalidad', models.CharField(max_length=20)),
                ('vacantes', models.IntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleos.categorias')),
                ('empresa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='empleos.empresa')),
                ('localidad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='empleos.localidad')),
            ],
            options={
                'ordering': ('-fecha_publicacion',),
            },
        ),
    ]
