# Generated by Django 4.2.3 on 2023-07-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('contenido', models.TextField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel_laboral', models.CharField(max_length=20)),
                ('carga_horaria', models.IntegerField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('modalidad', models.CharField(max_length=20)),
                ('vacantes', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.categoria')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.localidad')),
            ],
            options={
                'ordering': ('-fecha_publicacion',),
            },
        ),
    ]
