# Generated by Django 4.2.3 on 2023-07-20 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleo',
            old_name='titulo',
            new_name='puesto',
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('Localidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleos.localidad')),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleos.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='empleo',
            name='publicador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='empleos.empresa'),
            preserve_default=False,
        ),
    ]
