# Generated by Django 4.2.3 on 2023-07-23 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0002_rename_titulo_empleo_puesto_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
