# Generated by Django 4.2.3 on 2023-07-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0003_alter_empleo_fecha_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleo',
            old_name='publicador',
            new_name='empresa',
        ),
    ]
