# Generated by Django 4.2.3 on 2023-07-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0004_rename_publicador_empleo_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='Localidad',
            new_name='localidad',
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, default='usuarios/usuario_default.png', null=True, upload_to='empleos'),
        ),
    ]
