# Generated by Django 4.2.3 on 2023-07-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0005_rename_localidad_empresa_localidad_empresa_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='categoria',
        ),
    ]
