# Generated by Django 4.2.3 on 2023-07-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0006_remove_empresa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, default='empleos/logo_default.png', null=True, upload_to='empleos'),
        ),
    ]
