# Generated by Django 4.2.3 on 2023-07-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0007_alter_empresa_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
    ]
