# Generated by Django 4.2.3 on 2023-07-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0008_rename_categoria_categorias'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorias',
            table='categorias',
        ),
    ]
